RandoAmisSecours/urls.py
# -*- coding: utf-8 -*-
# vim: set ts=4

# Copyright 2013, 2014 Rémi Duraffort
# This file is part of RandoAmisSecours.
#
# RandoAmisSecours is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# RandoAmisSecours is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with RandoAmisSecours.  If not, see <http://www.gnu.org/licenses/>

from __future__ import unicode_literals

from django.conf.urls import include, url
from django.contrib.auth import views as r_auth
from django.core.urlresolvers import reverse_lazy
from tastypie.api import Api

from RandoAmisSecours.api import OutingResource, ProfileResource, UserResource, GPSPointResource, LoginResource
from RandoAmisSecours.views.account import RASAuthenticationForm, RASPasswordChangeForm, RASPasswordResetForm, RASSetPasswordForm

from RandoAmisSecours.views import account as r_account
from RandoAmisSecours.views import friends as r_friends
from RandoAmisSecours.views import help as r_help
from RandoAmisSecours.views import main as r_main
from RandoAmisSecours.views import outing as r_outing
from RandoAmisSecours.views import reporting as r_reporting


# API v1.0
api_1_0 = Api(api_name='1.0')
api_1_0.register(OutingResource())
api_1_0.register(ProfileResource())
api_1_0.register(UserResource())
api_1_0.register(GPSPointResource())
api_1_0.register(LoginResource())

urlpatterns = [
    # Main page
    url(r'^$', r_main.index, name='index'),

    # Help pages
    url(r'^help/$', r_help.index, name='help.index'),
    url(r'^help/qa/$', r_help.qa, name='help.qa'),

    # Authentication
    url(r'^accounts/login/$', r_auth.login, {'template_name': 'RandoAmisSecours/account/login.html', 'authentication_form': RASAuthenticationForm}, name='accounts.login'),
    url(r'^accounts/logout/$', r_auth.logout, {'template_name': 'RandoAmisSecours/account/logged_out.html'}, name='accounts.logout'),
    url(r'^accounts/password/change/$', r_auth.password_change, {'template_name': 'RandoAmisSecours/account/password_change.html', 'password_change_form': RASPasswordChangeForm, 'post_change_redirect': reverse_lazy('accounts.password_change_done')}, name='accounts.password_change'),
    url(r'^accounts/password/reset/$', r_auth.password_reset, {'template_name': 'RandoAmisSecours/account/password_reset.html', 'email_template_name': 'RandoAmisSecours/account/password_reset_email.txt', 'password_reset_form': RASPasswordResetForm, 'post_reset_redirect': reverse_lazy('accounts.password_reset_done')}, name='accounts.password_reset'),
    url(r'^accounts/password/reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', r_auth.password_reset_confirm, {'template_name': 'RandoAmisSecours/account/password_reset_confirm.html', 'set_password_form': RASSetPasswordForm}, name='accounts.password_reset_confirm'),
    url(r'^accounts/password/reset/complete/$', r_auth.password_reset_complete, {'template_name': 'RandoAmisSecours/account/password_reset_complete.html'}, name='password_reset_complete'),


    url(r'^accounts/register/$', r_account.register, name='accounts.register'),
    url(r'^accounts/register/(?P<user_id>\d+)/confirm/(?P<user_hash>\w+)/$', r_account.register_confirm, name='accounts.register.confirm'),
    url(r'^accounts/profile/$', r_account.profile, name='accounts.profile'),
    url(r'^accounts/profile/update/$', r_account.update, name='accounts.profile.update'),
    url(r'^accounts/password/change/done/$', r_account.password_change_done, name='accounts.password_change_done'),
    url(r'^accounts/password/reset/done/$', r_account.password_reset_done, name='accounts.password_reset_done'),
    url(r'^accounts/delete/$', r_account.delete, name='accounts.delete'),

    # Friends
    url(r'^friends/search/$', r_friends.search, name='friends.search'),
    url(r'^friends/invite/(?P<user_id>\d+)/$', r_friends.invite, name='friends.invite'),
    url(r'^friends/accept/(?P<request_id>\d+)/$', r_friends.accept, name='friends.accept'),
    url(r'^friends/refuse/(?P<request_id>\d+)/$', r_friends.refuse, name='friends.refuse'),
    url(r'^friends/cancel/(?P<request_id>\d+)/$', r_friends.cancel, name='friends.cancel'),
    url(r'^friends/delete/(?P<user_id>\d+)/$', r_friends.delete, name='friends.delete'),

    # Outings
    url(r'^outings/$', r_outing.index, name='outings.index'),
    url(r'^outings/create/$', r_outing.create, name='outings.create'),
    url(r'^outings/(?P<outing_id>\d+)/$', r_outing.details, name='outings.details'),
    url(r'^outings/(?P<outing_id>\d+)/trace/$', r_outing.details_trace, name='outings.details.trace'),
    url(r'^outings/(?P<outing_id>\d+)/update/$', r_outing.update, name='outings.update'),
    url(r'^outings/(?P<outing_id>\d+)/delete/$', r_outing.delete, name='outings.delete'),
    url(r'^outings/(?P<outing_id>\d+)/confirm/$', r_outing.confirm, name='outings.confirm'),
    url(r'^outings/(?P<outing_id>\d+)/finish/$', r_outing.finish, name='outings.finish'),

    # Reporting
    url(r'^reporting/$', r_reporting.index, name='reporting.index'),
    url(r'^reporting/users/$', r_reporting.users, name='reporting.users'),
    url(r'^reporting/outings/late/$', r_reporting.outings_late, name='reporting.outings.late'),

    # API
    url(r'^api/', include(api_1_0.urls)),
]

RandoAmisSecours/models.py
# -*- coding: utf-8 -*-
# vim: set ts=4

# Copyright 2013, 2014 Rémi Duraffort
# This file is part of RandoAmisSecours.
#
# RandoAmisSecours is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# RandoAmisSecours is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with RandoAmisSecours.  If not, see <http://www.gnu.org/licenses/>

from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.timezone import datetime, utc
from django.utils.translation import ugettext_noop as _
from django.utils.translation import ugettext

from RandoAmisSecours.settings import LANGUAGES
import binascii
import json
import pytz
import os


# Outing status
DRAFT = 0
CONFIRMED = 1
LATE = 3
FINISHED = 4
CANCELED = 5
OUTING_STATUS = (
    (DRAFT, _('draft')),
    (CONFIRMED, _('confirmed')),
    (LATE, _('late')),
    (FINISHED, _('finished')),
    (CANCELED, _('canceled'))
)

PROVIDERS = (
    ('mobile.free.fr', 'Free Mobile France'),
)


def random_hash():
    """ Create a random string of size 30 """
    return binascii.b2a_hex(os.urandom(15))


@python_2_unicode_compatible
class Profile(models.Model):
    class Meta:
        app_label = 'RandoAmisSecours'

    user = models.OneToOneField(User)
    friends = models.ManyToManyField('self', blank=True)
    phone_number = models.CharField(max_length=30, blank=True, null=True)
    provider = models.CharField(max_length=30, blank=True, null=True, choices=PROVIDERS)
    provider_data = models.TextField(blank=True, null=True)
    hash_id = models.CharField(unique=True, max_length=30, default=random_hash)
    language = models.CharField(max_length=4, blank=True, null=True, choices=LANGUAGES)
    timezone = models.CharField(max_length=40, choices=[(tz, tz) for tz in pytz.all_timezones], default='UTC')

    def clean(self):
        if self.provider_data:
            try:
                json.loads(self.provider_data)
            except Exception:
                raise ValidationError({'provider_data': [ugettext('This should be JSON serialized')]})

        if self.timezone == 'UTC':
            raise ValidationError({'timezone': [ugettext('UTC is not valid timezone')]})

    def __str__(self):
        return "%s" % (self.user)


@python_2_unicode_compatible
class FriendRequest(models.Model):
    class Meta:
        app_label = 'RandoAmisSecours'

    user = models.ForeignKey(User, related_name='+')
    to = models.ForeignKey(User, related_name='+')
    creation = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "%s => %s" % (self.user.get_full_name(), self.to.get_full_name())


@python_2_unicode_compatible
class Outing(models.Model):
    class Meta:
        app_label = 'RandoAmisSecours'
        ordering = ['beginning', 'ending', 'alert', 'name']

    user = models.ForeignKey(User)

    # Visible information
    name = models.CharField(max_length=200)
    description = models.TextField()
    status = models.IntegerField(choices=OUTING_STATUS, default=DRAFT)

    # Time frame: (begin, end, alert)
    beginning = models.DateTimeField()
    ending = models.DateTimeField()
    alert = models.DateTimeField()

    # Position on the map
    latitude = models.FloatField()
    longitude = models.FloatField()

    def __str__(self):
        return "%s: %s" % (self.user.get_full_name(), self.name)

    def getPercents(self):
        current_time = datetime.utcnow().replace(tzinfo=utc)
        # now < begin < end < alert
        if current_time < self.beginning:
            return (0, 0, 0)
        # begin < end < alert < now
        elif self.alert < current_time:
            return (0, 0, 100)
        # begin < now < end < alert
        elif current_time < self.ending:
            return (((current_time - self.beginning).total_seconds()) / float((self.alert - self.beginning).total_seconds()) * 100, 0, 0)
        # begin < end < now < alert
        else:
            assert(current_time < self.alert)
            return (((self.ending - self.beginning).total_seconds()) / float((self.alert - self.beginning).total_seconds()) * 100,
                    ((current_time - self.ending).total_seconds()) / float((self.alert - self.beginning).total_seconds()) * 100,
                    0)

    def is_running(self):
        """ Return True if beginning <= now < end """
        now = datetime.utcnow().replace(tzinfo=utc)
        return self.beginning <= now and now < self.ending

    def is_late(self):
        """ Return True if end <= now < alert """
        now = datetime.utcnow().replace(tzinfo=utc)
        return self.ending <= now and now < self.alert

    def is_alerting(self):
        """ Return True if alert <= now """
        now = datetime.utcnow().replace(tzinfo=utc)
        return self.alert <= now

    is_running.boolean = True
    is_late.boolean = True
    is_alerting.boolean = True


@python_2_unicode_compatible
class GPSPoint(models.Model):
    class Meta:
        app_label = 'RandoAmisSecours'
        ordering = ['date']

    outing = models.ForeignKey(Outing)
    date = models.DateTimeField()
    latitude = models.FloatField()
    longitude = models.FloatField()
    precision = models.IntegerField()

    def __str__(self):
        return "[%s] %s: (%f, %f)" % (self.outing.user.get_full_name(),
                                      self.outing.name, self.latitude,
                                      self.longitude)

RandoAmisSecours/templates/RandoAmisSecours/account/confirm.html
{% extends 'RandoAmisSecours/base.html' %}
{% load i18n %}

{% block title %}{% trans "Confirm" %}{% endblock %}

{% block nav-login %}active{% endblock %}

{% block head %}
  <meta http-equiv="refresh" content="5;url={% url 'accounts.login' %}">
{% endblock %}

{% block breadcrumb %}
  <li><a href="{% url 'index' %}">{% trans "Home" %}</a></li>
  <li><a href="{% url 'accounts.profile' %}">{% trans "Account" %}</a></li>
  <li class="activate">{% trans "Confirm" %}</li>
{% endblock %}

{% block body %}
<div class="page-header">
  <h1>{% trans "Registration confirmed" %}</h1>
</div>

<div class="row">
  <div class="col-md-12">
    <p class="lead">{% trans "Thanks for registering to R.A.S." %}</p>
    {% url 'accounts.login' as URL %}
    <p>{% blocktrans %}You will be <a href="{{ URL }}">redirected</a> to the login page in 5 seconds ...{% endblocktrans %}</p>
  </div>
</div>
{% endblock %}

RandoAmisSecours/templates/RandoAmisSecours/account/logged_out.html
{% extends 'RandoAmisSecours/base.html' %}
{% load i18n %}

{% block title %}{% trans "Logged out" %}{% endblock %}

{% block style %}
    .div-signout {
      max-width: 300px;
      padding: 19px 29px 29px;
      margin: 0 auto 20px;
      background-color: #fff;
      border: 1px solid #e5e5e5;
      -webkit-border-radius: 5px;
        -moz-border-radius: 5px;
             border-radius: 5px;
      -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.05);
         -moz-box-shadow: 0 1px 2px rgba(0,0,0,.05);
              box-shadow: 0 1px 2px rgba(0,0,0,.05);
      }
      .div-signout .div-signout-heading,
        margin-bottom: 10px;
      }
{% endblock %}

{% block nav-login %}active{% endblock %}

{% block breadcrumb %}
  <li><a href="{% url 'index' %}">{% trans "Home" %}</a></li>
  <li><a href="{% url 'accounts.profile' %}">{% trans "Account" %}</a></li>
  <li class="activate">{% trans "Log out" %}</li>
{% endblock %}

{% block body %}
<div class="container">
  <div class="div-signout">
    <h2 class="div-signout-heading">{% trans "Logged out" %}</h2>
    <p>{% trans "Thanks for using RandoAmisSecours." %}</p>
    <a href="{% url 'accounts.login' %}" class="btn btn-primary">{% trans "Log in again" %}</a>
  </div>
</div>
{% endblock %}

RandoAmisSecours/templates/RandoAmisSecours/account/login.html
{% extends 'RandoAmisSecours/base.html' %}
{% load i18n %}

{% block title %}{% trans "Log in" %}{% endblock %}

{% block style %}
  .form-signin {
    max-width: 300px;
    padding: 19px 29px 29px;
    margin: 0 auto 20px;
    background-color: #fff;
    border: 1px solid #e5e5e5;
    -webkit-border-radius: 5px;
       -moz-border-radius: 5px;
            border-radius: 5px;
    -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.05);
       -moz-box-shadow: 0 1px 2px rgba(0,0,0,.05);
            box-shadow: 0 1px 2px rgba(0,0,0,.05);
  }
  .form-signin .form-signin-heading,
  .form-signin .checkbox {
    margin-bottom: 10px;
  }
  .form-signin input[type="text"],
  .form-signin input[type="password"] {
    font-size: 16px;
    height: auto;
    margin-bottom: 15px;
    padding: 7px 9px;
  }
{% endblock %}

{% block nav-login %}active{% endblock %}

{% block breadcrumb %}
  <li><a href="{% url 'index' %}">{% trans "Home" %}</a></li>
  <li><a href="{% url 'accounts.profile' %}">{% trans "Account" %}</a></li>
  <li class="activate">{% trans "Log in" %}</li>
{% endblock %}

{% block body %}
<div class="container">
  {% if form.errors %}
    <div class="alert alert-danger">
      <button class="close" data-dismiss="alert" type="button">&times;</button>
      {% trans "<strong>Wrong username or password</strong>: Note that both fields may be case-sensitive" %}
    </div>
  {% endif %}

  <form class="form-signin" method="post" action="{% url 'accounts.login' %}">
    {% csrf_token %}
    <h2 class="form-signin-heading">{% trans "Please sign in" %}</h2>
      {{ form.username }}
      {{ form.password }}
    <button class="btn btn-large btn-primary" type="submit">{% trans "Log in" %}</button>
    <input type="hidden" name="next" value="{{ next }}" />
    <a href="{% url 'accounts.register' %}">{% trans "Create an account" %}</a>
  </form>
  <div class="form-signin">
    <p>{% trans "Forgotten your password?" %}</p>
    <p>{% trans "Request a new one:" %}<br /><a href="{% url 'accounts.password_reset' %}">{% trans "Password reset" %}</a></p>
  </div>
</div>
{% endblock %}

RandoAmisSecours/templates/RandoAmisSecours/account/password_change.html
{% extends 'RandoAmisSecours/base.html' %}
{% load i18n %}

{% block title %}{% trans "Change password" %}{% endblock %}

{% block nav-account %}active{% endblock %}

{% block breadcrumb %}
  <li><a href="{% url 'index' %}">{% trans "Home" %}</a></li>
  <li><a href="{% url 'accounts.profile' %}">{% trans "Account" %}</a></li>
  <li class="activate">{% trans "Change password" %}</li>
{% endblock %}

{% block body %}
<div class="page-header">
  <h1>{% trans "Change password" %}</h1>
</div>

<div class="row">
<div class="col-md-12">
  <form class="form-horizontal" role="form" action="." method="post">
    {% csrf_token %}
    <div class="form-group{% if form.old_password.errors %} has-error{% endif %}">
      <label class="col-md-2 control-label" for="id_old_password">{% trans "Old password" %}</label>
      <div class="col-md-4">
        {{ form.old_password }}
        {% for error in form.old_password.errors %}
        <p class="help-block">{{ error }}</p>
        {% endfor %}
      </div>
    </div>
    <div class="form-group{% if form.new_password1.errors %} has-error{% endif %}">
      <label class="col-md-2 control-label" for="id_new_password1">{% trans "New password" %}</label>
      <div class="col-md-4">
        {{ form.new_password1 }}
        {% for error in form.new_password1.errors %}
        <p class="help-block">{{ error }}</p>
        {% endfor %}
      </div>
    </div>
    <div class="form-group{% if form.new_password2.errors %} has-error{% endif %}">
      <label class="col-md-2 control-label" for="id_new_password2">{% trans "New password" %}</label>
      <div class="col-md-4">
        {{ form.new_password2 }}
        {% for error in form.new_password2.errors %}
        <p class="help-block">{{ error }}</p>
        {% endfor %}
      </div>
    </div>
    <div class="form-group">
      <div class="col-md-6 col-md-offset-2">
        <button class="btn btn-primary" type="submit">{% trans "Change" %}</button>
      </div>
    </div>
  </form>
</div>
</div>
{% endblock %}

RandoAmisSecours/templates/RandoAmisSecours/account/password_reset.html
{% extends 'RandoAmisSecours/base.html' %}
{% load i18n %}

{% block title %}{% trans "Password reset" %}{% endblock %}

{% block nav-login %}active{% endblock %}

{% block breadcrumb %}
  <li><a href="{% url 'index' %}">{% trans "Home" %}</a></li>
  <li><a href="{% url 'accounts.profile' %}">{% trans "Account" %}</a></li>
  <li class="activate">{% trans "Password reset" %}</li>
{% endblock %}

{% block body %}
<div class="page-header">
  <h1>{% trans "Password reset" %}</h1>
</div>

<div class="row">
  <div class="col-md-12">
    <p>{% trans "Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one." %}</p>
    <form class="form-horizontal" role="form" action="." method="post">
      {% csrf_token %}
      <div class="form-group{% if form.email.errors %} has-error{% endif %}">
        <label class="col-md-4 control-label" for="id_email">{% trans "Email address:" %}</label>
        <div class="col-md-4">
          {{ form.email }}
          {% for error in form.email.errors %}
          <p class="help-block">{{ error }}</p>
          {% endfor %}
        </div>
      </div>
      <div class="form-group">
        <div class="col-md-8 col-md-offset-4">
          <button type="submit" class="btn btn-primary">{% trans "Reset my password" %}</button>
        </div>
      </div>
    </form>
  </div>
</div>
{% endblock %}

RandoAmisSecours/templates/RandoAmisSecours/account/password_reset_complete.html
{% extends 'RandoAmisSecours/base.html' %}
{% load i18n %}

{% block title %}{% trans "Password reset complete" %}{% endblock %}

{% block nav-login %}active{% endblock %}

{% block breadcrumb %}
  <li><a href="{% url 'index' %}">{% trans "Home" %}</a></li>
  <li><a href="{% url 'accounts.profile' %}">{% trans "Account" %}</a></li>
  <li class="activate">{% trans "Password reset" %}</li>
{% endblock %}

{% block body %}
<div class="page-header">
  <h1>{% trans "Password reset complete" %}</h1>
</div>

<div class="row">
  <div class="col-md-12">
    <p>{% trans "Your password has been set.  You may go ahead and log in now." %}</p>
    <p><a href="{{ login_url }}">{% trans "Log in" %}</a></p>
  </div>
</div>
{% endblock %}

RandoAmisSecours/templates/RandoAmisSecours/account/register_email.html
{% load i18n %}{% blocktrans %}Hello {{ fullname }},

Thanks for registering to R.A.S.
In order to activate your account, click on the confirmation link: {{ URL }}.

If you haven't registered to R.A.S., just delete this mail and the registration will be canceled.

-- 
The R.A.S. team{% endblocktrans %}

RandoAmisSecours/templates/RandoAmisSecours/account/update.html
{% extends 'RandoAmisSecours/base.html' %}
{% load i18n static %}

{% block title %}{% trans "Update" %}{% endblock %}

{% block nav-account %}active{% endblock %}

{% block breadcrumb %}
  <li><a href="{% url 'index' %}">{% trans "Home" %}</a></li>
  <li><a href="{% url 'accounts.profile' %}">{% trans "Account" %}</a></li>
  <li class="activate">{% trans "Update" %}</li>
{% endblock %}

{% block body %}
<div class="page-header">
  <h1>{% trans "Update my account" %}</h1>
</div>

{% if messages %}
<div class="span12">
  {% for message in messages %}
  <div class="alert alert-{{ message.tags|default:'danger' }}">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <strong>{{ message.tags|default:'danger'|capfirst }}:</strong> {{ message }}
  </div>
  {% endfor %}
</div>
{% endif %}


<div class="row">
  <form class="form-horizontal" tole="form" method="post" action="{% url 'accounts.profile.update' %}">
  {% csrf_token %}
  <div class="col-md-6">
    <h4 class="modal-header">{% trans "Personnal information" %}</h4>
    <div class="form-group {% if user_form.first_name.errors %} has-error{% endif %}">
      <label class="col-md-4 control-label" for="id_first_name">{% trans "First name" %}</label>
      <div class="col-md-8">
        {{ user_form.first_name }}
        {% for error in user_form.first_name.errors %}
        <p class="help-block">{{ error }}</p>
        {% endfor %}
      </div>
    </div>
    <div class="form-group{% if user_form.last_name.errors %} has-error{% endif %}">
      <label class="col-md-4 control-label" for="id_last_name">{% trans "Last name" %}</label>
      <div class="col-md-8">
        {{ user_form.last_name }}
        {% for error in user_form.last_name.errors %}
        <p class="help-block">{{ error }}</p>
        {% endfor %}
      </div>
    </div>
    <div class="form-group{% if profile_form.phone_number.errors %} has-error{% endif %}">
      <label class="col-md-4 control-label" for="id_phone_number">{% trans "Phone number" %}</label>
      <div class="col-md-8">
        {{ profile_form.phone_number }}
        {% for error in profile_form.phone_number.errors %}
        <p class="help-block">{{ error }}</p>
        {% endfor %}
      </div>
    </div>
  </div>
  <div class="col-md-6">
    <h4 class="modal-header">{% trans "Localization" %}</h4>
    <div class="form-group{% if profile_form.language.errors %} has-error{% endif %}">
      <label class="col-md-4 control-label" for="id_language">{% trans "Language" %}</label>
      <div class="col-md-8">
        <select class="form-control" id="id_language" name="language">
          {% for value, text in profile_form.language.field.choices %}
          <option value="{{ value }}"{% if value == user.profile.language %} selected="selected"{% endif %}>{% trans text %}</option>
          {% endfor %}
        </select>
        {% for error in profile_form.language.errors %}
        <p class="help-block">{{ error }}</p>
        {% endfor %}
      </div>
    </div>
    <div class="form-group{% if profile_form.timezone.errors %} has-error{% endif %}">
      <label class="col-md-4 control-label" for="id_timezone">{% trans "Timezone" %}</label>
      <div class="col-md-8">
        {{ profile_form.timezone }}
        {% for error in profile_form.timezone.errors %}
        <p class="help-block">{{ error }}</p>
        {% endfor %}
        <p>{% blocktrans %}Your browser is in the same timezone as <u id="current_timezone"></u>{% endblocktrans %}</p>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-6">
    <h4 class="modal-header">{% trans "Advanced settings" %}</h4>
    <p>{% trans "Some providers, allows to send SMS from R.A.S. to you phone for free. Select your provider in the following list (if available) to receive alerts by SMS." %}</p>
    <div class="form-group{% if profile_form.provider.errors %} has-error{% endif %}">
      <label class="col-md-4 control-label" for="id_provider">{% trans "Provider" %}</label>
      <div class="col-md-8">
        {{ profile_form.provider }}
        {% for error in profile_form.provider.errors %}
        <p class="help-block">{{ error }}</p>
        {% endfor %}
      </div>
    </div>
    <div id="MobileFreeFr" class="hidden">
      <p>{% blocktrans %}In order to get the following information, you should activate the option called <i>SMS Notification</i> on <a href="https://mobile.free.fr/moncompte/index.php?page=options">your option page</a>. Then enter the generated user key in the <i>token</i> field.{% endblocktrans %}</p>
      <div class="form-group" id="form_group_mobile_free_fr_user">
        <label class="col-md-4 control-label" for="id_mobile_free_fr_user">{% trans "Username" %}</label>
        <div class="col-md-8">
           <input class="form-control" id="id_mobile_free_fr_user" maxlength="30" name="username" type="text" />
        </div>
      </div>
      <div class="form-group" id="form_group_mobile_free_fr_token">
        <label class="col-md-4 control-label" for="id_mobile_free_fr_token">{% trans "Token" %}</label>
        <div class="col-md-8">
           <input class="form-control" id="id_mobile_free_fr_token" maxlength="30" name="token" type="text" />
        </div>
      </div>
    </div>
  </div>

  {{ profile_form.provider_data }}
  <div class="form-group">
    <div class="col-md-10 col-md-offset-2">
      <button class="btn btn-primary" type="submit" id="btn_submit">{% trans "Update" %}</button>
    </div>
  </div>
  </form>
</div>
{% endblock %}

{% block script %}
<script src="{% get_static_prefix %}RandoAmisSecours/js/jstz-v1.0.6.min.js"></script>
<script>
  $(function(){
    var timezone = jstz.determine();
    $('#current_timezone').html(timezone.name());

    var MobileFreeFrClick = function() {
      var user = $('#id_mobile_free_fr_user').val();
      var token = $('#id_mobile_free_fr_token').val();
      if(user == '' || token == '') {
        if(user == '') {
          $('#form_group_mobile_free_fr_user').addClass('has-error');
        } else {
          $('#form_group_mobile_free_fr_user').removeClass('has-error');
        }
        if(token == '') {
          $('#form_group_mobile_free_fr_token').addClass('has-error');
        } else {
          $('#form_group_mobile_free_fr_token').removeClass('has-error');
        }

        return false;
      }
      // transform into JSON
      $('#id_provider_data').val(JSON.stringify({'user': user, 'token': token}));

    };

    // Check the current value
    if($('#id_provider').val() == 'mobile.free.fr') {
        var data = JSON.parse($('#id_provider_data').val());
        $('#id_mobile_free_fr_user').val(data['user']);
        $('#id_mobile_free_fr_token').val(data['token']);

        $('#MobileFreeFr').removeClass('hidden');
        $('#btn_submit').click(MobileFreeFrClick);
    }

    // Handle clicks on the sect
    $('#id_provider').change(function() {
      var selected_text = $( "#id_provider option:selected" ).val();
      if(selected_text == 'mobile.free.fr') {
        $('#MobileFreeFr').removeClass('hidden');
        $('#btn_submit').click(MobileFreeFrClick);
      } else {
        $('#MobileFreeFr').addClass('hidden');
        $('#btn_submit').unbind('click', MobileFreeFrClick);
      }
    });
  });
</script>
{% endblock %}