RandoAmisSecours/urls.py
# -*- coding: utf-8 -*-
# vim: set ts=4

# Copyright 2013, 2014 Rémi Duraffort
# This file is part of RandoAmisSecours.
#
# RandoAmisSecours is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# RandoAmisSecours is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with RandoAmisSecours.  If not, see <http://www.gnu.org/licenses/>

from __future__ import unicode_literals

from django.conf.urls import include, url
from django.contrib.auth import views as r_auth
from django.core.urlresolvers import reverse_lazy
from tastypie.api import Api

from RandoAmisSecours.api import OutingResource, ProfileResource, UserResource, GPSPointResource, LoginResource
from RandoAmisSecours.views.account import RASAuthenticationForm, RASPasswordChangeForm, RASPasswordResetForm, RASSetPasswordForm

from RandoAmisSecours.views import account as r_account
from RandoAmisSecours.views import friends as r_friends
from RandoAmisSecours.views import help as r_help
from RandoAmisSecours.views import main as r_main
from RandoAmisSecours.views import outing as r_outing
from RandoAmisSecours.views import reporting as r_reporting


# API v1.0
api_1_0 = Api(api_name='1.0')
api_1_0.register(OutingResource())
api_1_0.register(ProfileResource())
api_1_0.register(UserResource())
api_1_0.register(GPSPointResource())
api_1_0.register(LoginResource())

urlpatterns = [
    # Main page
    url(r'^$', r_main.index, name='index'),

    # Help pages
    url(r'^help/$', r_help.index, name='help.index'),
    url(r'^help/qa/$', r_help.qa, name='help.qa'),

    # Authentication
    url(r'^accounts/login/$', r_auth.login, {'template_name': 'RandoAmisSecours/account/login.html', 'authentication_form': RASAuthenticationForm}, name='accounts.login'),
    url(r'^accounts/logout/$', r_auth.logout, {'template_name': 'RandoAmisSecours/account/logged_out.html'}, name='accounts.logout'),
    url(r'^accounts/password/change/$', r_auth.password_change, {'template_name': 'RandoAmisSecours/account/password_change.html', 'password_change_form': RASPasswordChangeForm, 'post_change_redirect': reverse_lazy('accounts.password_change_done')}, name='accounts.password_change'),
    url(r'^accounts/password/reset/$', r_auth.password_reset, {'template_name': 'RandoAmisSecours/account/password_reset.html', 'email_template_name': 'RandoAmisSecours/account/password_reset_email.txt', 'password_reset_form': RASPasswordResetForm, 'post_reset_redirect': reverse_lazy('accounts.password_reset_done')}, name='accounts.password_reset'),
    url(r'^accounts/password/reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', r_auth.password_reset_confirm, {'template_name': 'RandoAmisSecours/account/password_reset_confirm.html', 'set_password_form': RASSetPasswordForm}, name='accounts.password_reset_confirm'),
    url(r'^accounts/password/reset/complete/$', r_auth.password_reset_complete, {'template_name': 'RandoAmisSecours/account/password_reset_complete.html'}, name='password_reset_complete'),


    url(r'^accounts/register/$', r_account.register, name='accounts.register'),
    url(r'^accounts/register/(?P<user_id>\d+)/confirm/(?P<user_hash>\w+)/$', r_account.register_confirm, name='accounts.register.confirm'),
    url(r'^accounts/profile/$', r_account.profile, name='accounts.profile'),
    url(r'^accounts/profile/update/$', r_account.update, name='accounts.profile.update'),
    url(r'^accounts/password/change/done/$', r_account.password_change_done, name='accounts.password_change_done'),
    url(r'^accounts/password/reset/done/$', r_account.password_reset_done, name='accounts.password_reset_done'),
    url(r'^accounts/delete/$', r_account.delete, name='accounts.delete'),

    # Friends
    url(r'^friends/search/$', r_friends.search, name='friends.search'),
    url(r'^friends/invite/(?P<user_id>\d+)/$', r_friends.invite, name='friends.invite'),
    url(r'^friends/accept/(?P<request_id>\d+)/$', r_friends.accept, name='friends.accept'),
    url(r'^friends/refuse/(?P<request_id>\d+)/$', r_friends.refuse, name='friends.refuse'),
    url(r'^friends/cancel/(?P<request_id>\d+)/$', r_friends.cancel, name='friends.cancel'),
    url(r'^friends/delete/(?P<user_id>\d+)/$', r_friends.delete, name='friends.delete'),

    # Outings
    url(r'^outings/$', r_outing.index, name='outings.index'),
    url(r'^outings/create/$', r_outing.create, name='outings.create'),
    url(r'^outings/(?P<outing_id>\d+)/$', r_outing.details, name='outings.details'),
    url(r'^outings/(?P<outing_id>\d+)/trace/$', r_outing.details_trace, name='outings.details.trace'),
    url(r'^outings/(?P<outing_id>\d+)/update/$', r_outing.update, name='outings.update'),
    url(r'^outings/(?P<outing_id>\d+)/delete/$', r_outing.delete, name='outings.delete'),
    url(r'^outings/(?P<outing_id>\d+)/confirm/$', r_outing.confirm, name='outings.confirm'),
    url(r'^outings/(?P<outing_id>\d+)/finish/$', r_outing.finish, name='outings.finish'),

    # Reporting
    url(r'^reporting/$', r_reporting.index, name='reporting.index'),
    url(r'^reporting/users/$', r_reporting.users, name='reporting.users'),
    url(r'^reporting/outings/late/$', r_reporting.outings_late, name='reporting.outings.late'),

    # API
    url(r'^api/', include(api_1_0.urls)),
]

RandoAmisSecours/models.py
# -*- coding: utf-8 -*-
# vim: set ts=4

# Copyright 2013, 2014 Rémi Duraffort
# This file is part of RandoAmisSecours.
#
# RandoAmisSecours is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# RandoAmisSecours is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with RandoAmisSecours.  If not, see <http://www.gnu.org/licenses/>

from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.timezone import datetime, utc
from django.utils.translation import ugettext_noop as _
from django.utils.translation import ugettext

from RandoAmisSecours.settings import LANGUAGES
import binascii
import json
import pytz
import os


# Outing status
DRAFT = 0
CONFIRMED = 1
LATE = 3
FINISHED = 4
CANCELED = 5
OUTING_STATUS = (
    (DRAFT, _('draft')),
    (CONFIRMED, _('confirmed')),
    (LATE, _('late')),
    (FINISHED, _('finished')),
    (CANCELED, _('canceled'))
)

PROVIDERS = (
    ('mobile.free.fr', 'Free Mobile France'),
)


def random_hash():
    """ Create a random string of size 30 """
    return binascii.b2a_hex(os.urandom(15))


@python_2_unicode_compatible
class Profile(models.Model):
    class Meta:
        app_label = 'RandoAmisSecours'

    user = models.OneToOneField(User)
    friends = models.ManyToManyField('self', blank=True)
    phone_number = models.CharField(max_length=30, blank=True, null=True)
    provider = models.CharField(max_length=30, blank=True, null=True, choices=PROVIDERS)
    provider_data = models.TextField(blank=True, null=True)
    hash_id = models.CharField(unique=True, max_length=30, default=random_hash)
    language = models.CharField(max_length=4, blank=True, null=True, choices=LANGUAGES)
    timezone = models.CharField(max_length=40, choices=[(tz, tz) for tz in pytz.all_timezones], default='UTC')

    def clean(self):
        if self.provider_data:
            try:
                json.loads(self.provider_data)
            except Exception:
                raise ValidationError({'provider_data': [ugettext('This should be JSON serialized')]})

        if self.timezone == 'UTC':
            raise ValidationError({'timezone': [ugettext('UTC is not valid timezone')]})

    def __str__(self):
        return "%s" % (self.user)


@python_2_unicode_compatible
class FriendRequest(models.Model):
    class Meta:
        app_label = 'RandoAmisSecours'

    user = models.ForeignKey(User, related_name='+')
    to = models.ForeignKey(User, related_name='+')
    creation = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "%s => %s" % (self.user.get_full_name(), self.to.get_full_name())


@python_2_unicode_compatible
class Outing(models.Model):
    class Meta:
        app_label = 'RandoAmisSecours'
        ordering = ['beginning', 'ending', 'alert', 'name']

    user = models.ForeignKey(User)

    # Visible information
    name = models.CharField(max_length=200)
    description = models.TextField()
    status = models.IntegerField(choices=OUTING_STATUS, default=DRAFT)

    # Time frame: (begin, end, alert)
    beginning = models.DateTimeField()
    ending = models.DateTimeField()
    alert = models.DateTimeField()

    # Position on the map
    latitude = models.FloatField()
    longitude = models.FloatField()

    def __str__(self):
        return "%s: %s" % (self.user.get_full_name(), self.name)

    def getPercents(self):
        current_time = datetime.utcnow().replace(tzinfo=utc)
        # now < begin < end < alert
        if current_time < self.beginning:
            return (0, 0, 0)
        # begin < end < alert < now
        elif self.alert < current_time:
            return (0, 0, 100)
        # begin < now < end < alert
        elif current_time < self.ending:
            return (((current_time - self.beginning).total_seconds()) / float((self.alert - self.beginning).total_seconds()) * 100, 0, 0)
        # begin < end < now < alert
        else:
            assert(current_time < self.alert)
            return (((self.ending - self.beginning).total_seconds()) / float((self.alert - self.beginning).total_seconds()) * 100,
                    ((current_time - self.ending).total_seconds()) / float((self.alert - self.beginning).total_seconds()) * 100,
                    0)

    def is_running(self):
        """ Return True if beginning <= now < end """
        now = datetime.utcnow().replace(tzinfo=utc)
        return self.beginning <= now and now < self.ending

    def is_late(self):
        """ Return True if end <= now < alert """
        now = datetime.utcnow().replace(tzinfo=utc)
        return self.ending <= now and now < self.alert

    def is_alerting(self):
        """ Return True if alert <= now """
        now = datetime.utcnow().replace(tzinfo=utc)
        return self.alert <= now

    is_running.boolean = True
    is_late.boolean = True
    is_alerting.boolean = True


@python_2_unicode_compatible
class GPSPoint(models.Model):
    class Meta:
        app_label = 'RandoAmisSecours'
        ordering = ['date']

    outing = models.ForeignKey(Outing)
    date = models.DateTimeField()
    latitude = models.FloatField()
    longitude = models.FloatField()
    precision = models.IntegerField()

    def __str__(self):
        return "[%s] %s: (%f, %f)" % (self.outing.user.get_full_name(),
                                      self.outing.name, self.latitude,
                                      self.longitude)

RandoAmisSecours/templates/RandoAmisSecours/outing/create.html
{% extends 'RandoAmisSecours/base.html' %}
{% load static i18n %}

{% block title %}{{ update|yesno:_("Update,New outing") }}{% endblock %}

{% block head %}
  <link rel="stylesheet" type="text/css" href="{% get_static_prefix %}RandoAmisSecours/css/leaflet-v0.7.7.css" />
  <link rel="stylesheet" href="{% get_static_prefix %}RandoAmisSecours/css/leaflet.fullscreen-v1.0.1.css" />
  <link rel="stylesheet" type="text/css" href="{% get_static_prefix %}RandoAmisSecours/css/l.geosearch-e073626.css" />
  <link rel="stylesheet" type="text/css" href="{% get_static_prefix %}RandoAmisSecours/css/bootstrap-datetimepicker-v2.2.0.css" />
{% endblock %}

{% block style %}
    #map { height: 400px; }
{% endblock %}

{% block nav-outings %}active{% endblock %}

{% block breadcrumb %}
  <li><a href="{% url 'index' %}">{% trans "Home" %}</a></li>
  <li><a href="{% url 'outings.index' %}">{% trans "Outings" %}</a></li>
  <li class="active">{{ update|yesno:_("Update,Create") }}</li>
{% endblock %}

{% block body %}
<h2>{% if update %}{% blocktrans with outing.name as name %}Update «{{ name }}»{% endblocktrans %}{% else %}{% trans "New outing" %}{% endif %}</h2>

<div class="row">
  <div class="col-md-12">
  <form class="form-horizontal" role="form" action="." method="post">
    {% csrf_token %}
    <div class="row">
      <div class="col-md-6">
        <h4 class="modal-header">{% trans "Global information" %}</h4>
        <div class="form-group{% if form.name.errors %} has-error{% endif %}">
          <label class="col-md-4 control-label" for="id_name">{% trans "Name" %}</label>
          <div class="col-md-8">
            {{ form.name }}
            {% for error in form.name.errors %}
            <p class="help-block">{{ error }}</p>
            {% endfor %}
          </div>
        </div>
        <div class="form-group{% if form.description.errors %} has-error{% endif %}">
          <label class="col-md-4 control-label" for="id_description">{% trans "Description" %}</label>
          <div class="col-md-8">
            {{ form.description }}
            {% for error in form.description.errors %}
            <p class="help-block">{{ error }}</p>
            {% endfor %}
          </div>
        </div>
        <div class="form-group{% if form.latitude.errors %} has-error{% endif %}">
          <label class="col-md-4 control-label" for="id_latitude">{% trans "Latitude" %}</label>
          <div class="col-md-8">
            {{ form.latitude }}
            {% for error in form.latitude.errors %}
            <p class="help-block">{{ error }}</p>
            {% endfor %}
          </div>
        </div>
        <div class="form-group{% if form.longitude.errors %} has-error{% endif %}">
          <label class="col-md-4 control-label" for="id_longitude">{% trans "Longitude" %}</label>
          <div class="col-md-8">
            {{ form.longitude }}
            {% for error in form.longitude.errors %}
            <p class="help-block">{{ error }}</p>
            {% endfor %}
          </div>
        </div>
      </div>
      <div class="col-md-6">
        <h4 class="modal-header">{% blocktrans with user.profile.timezone as TIME_ZONE %}Timing (in {{ TIME_ZONE }}){% endblocktrans %}</h4>
        <div class="form-group{% if form.beginning.errors %} has-error{% endif %}">
          <label class="col-md-4 control-label" for="id_beginning">{% trans "Begin" %}</label>
          <div class="col-md-8">
            <div id="beginning_picker" class="input-group date">
              {{ form.beginning }}
              <span class="input-group-addon"><span class="glyphicon glyphicon-th"></span></span>
            </div>
            {% for error in form.beginning.errors %}
            <p class="help-block">{{ error }}</p>
            {% endfor %}
          </div>
        </div>
        <div class="form-group{% if form.ending.errors %} has-error{% endif %}">
          <label class="col-md-4 control-label" for="id_ending">{% trans "End" %}</label>
          <div class="col-md-8">
            <div id="ending_picker" class="input-group date">
              {{ form.ending }}
              <span class="input-group-addon"><span class="glyphicon glyphicon-th"></span></span>
            </div>
            {% for error in form.ending.errors %}
            <p class="help-block">{{ error }}</p>
            {% endfor %}
          </div>
        </div>
        <div class="form-group{% if form.alert.errors %} has-error{% endif %}">
          <label class="col-md-4 control-label" for="id_alert">{% trans "Alert" %}</label>
          <div class="col-md-8">
            <div id="alert_picker" class="input-group date">
              {{ form.alert }}
              <span class="input-group-addon"><span class="glyphicon glyphicon-th"></span></span>
            </div>
            {% for error in form.alert.errors %}
            <p class="help-block">{{ error }}</p>
            {% endfor %}
          </div>
        </div>
        <p>{% trans "RandoAmisSecours will use the three fields above to decide upon when to send email:" %}</p>
        <dl class="dl-horizontal">
          <dt>{% trans "Beginning" %}</dt>
          <dd>{% trans "the beginning of the outing" %}</dd>
          <dt>{% trans "Ending" %}</dt>
          <dd>{% trans "the planned ending" %}</dd>
          <dt>{% trans "Alert" %}</dt>
          <dd>{% trans "the time to alert friends" %}</dd>
        </dl>
        <p>{% trans "After the ending R.A.S. sends emails to the owner. After the alert, friends are also emailed until the outing is closed." %}</p>
      </div>
      <div class="col-md-8 col-md-offset-2">
        <div id="map">
        </div>
      </div>
    </div>
    <div class="form-group">
      <div class="col-md-10 col-md-offset-2">
        <button type="submit" class="btn btn-primary">{{ update|yesno:_("Update,Create") }}</button>
      </div>
    </div>
  </form>
  </div>
</div>
{% endblock %}

{% block script %}
<script src="{% get_static_prefix %}RandoAmisSecours/js/leaflet-v0.7.7.js"></script>
<script src="{% get_static_prefix %}RandoAmisSecours/js/Leaflet.fullscreen.min-v1.0.1.js"></script>
<script src="{% get_static_prefix %}RandoAmisSecours/js/l.control.geosearch-e073626.js"></script>
<script src="{% get_static_prefix %}RandoAmisSecours/js/l.geosearch.provider.openstreetmap-e073626.js"></script>
<script src="{% get_static_prefix %}RandoAmisSecours/js/bootstrap-datetimepicker-v2.2.0.js"></script>
{% get_current_language as LANGUAGE_CODE_LONG %}
{% with LANGUAGE_CODE_LONG|slice:"0:2" as LANGUAGE_CODE %}
{% if LANGUAGE_CODE == 'fr' %}<script src="{% get_static_prefix %}RandoAmisSecours/js/locales/bootstrap-datetimepicker-v2.2.0.fr.js"></script>{% endif %}
{% if LANGUAGE_CODE == 'es' %}<script src="{% get_static_prefix %}RandoAmisSecours/js/locales/bootstrap-datetimepicker-v2.2.0.es.js"></script>{% endif %}
{% endwith %}
<script>
  $(function(){
    var basemap = new L.TileLayer('//{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
                        {attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors',
                         maxZoom: 18});
    var marker = null;
    var map = new L.Map('map', {
      layers: [basemap],
      center: new L.LatLng(0, 0),
      zoom: 1,
      fullscreenControl: {
        pseudoFullscreen: true
    }
    });

    new L.Control.GeoSearch({
      provider: new L.GeoSearch.Provider.OpenStreetMap(),
      showMarker: false
    }).addTo(map);

    // Add a marker to the map
    function addMarker(latlng) {
      marker = L.marker(latlng,  {'draggable': true}).addTo(map);
      // Update the postion while dragging
      marker.on('dragend', function(e) {
        var latlng = marker.getLatLng();
        $('#id_latitude').val(latlng.lat);
        $('#id_longitude').val(latlng.lng);
      });
      marker.on('drag', function(e) {
        var latlng = marker.getLatLng();
        $('#id_latitude').val(latlng.lat);
        $('#id_longitude').val(latlng.lng);
      });
    }

    // Add the marker at the right place if latitude and longitude are defined
    if($('#id_latitude').val() && $('#id_longitude').val()) {
      addMarker([$('#id_latitude').val(), $('#id_longitude').val()]);
    }

    // Map events
    map.on('click', function(e){
      // Update the position when clicking
      $('#id_latitude').val(e.latlng.lat);
      $('#id_longitude').val(e.latlng.lng);

      // Create the marker if needed
      if(!marker) {
        addMarker(e.latlng);
      } else {
        marker.setLatLng(e.latlng);
      }
    });

    // datetime pickers
    $('#beginning_picker').datetimepicker({
      todayBtn: true,
      language: '{{ LANGUAGE_CODE }}',
      autoclose: true,
      minuteStep: 15,
      pickerPosition: "bottom-left",
      format: "{% trans "yyyy-mm-dd hh:ii:ss" %}"
    }).on('changeDate', function(ev){
        var start_date = new Date(ev.date.valueOf() + 60000 * ev.date.getTimezoneOffset());
        $('#ending_picker, #alert_picker').datetimepicker('setStartDate', start_date);
    });
    $('#ending_picker').datetimepicker({
      todayBtn: true,
      language: '{{ LANGUAGE_CODE }}',
      autoclose: true,
      minuteStep: 15,
      pickerPosition: "bottom-left",
      format: "{% trans "yyyy-mm-dd hh:ii:ss" %}"
    }).on('changeDate', function(ev){
        var start_date = new Date(ev.date.valueOf() + 60000 * ev.date.getTimezoneOffset());
        $('#alert_picker').datetimepicker('setStartDate', start_date);
    });
    $('#alert_picker').datetimepicker({
      todayBtn: true,
      language: '{{ LANGUAGE_CODE }}',
      autoclose: true,
      minuteStep: 15,
      pickerPosition: "bottom-left",
      format: "{% trans "yyyy-mm-dd hh:ii:ss" %}"
    });
  });
</script>
{% endblock %}

RandoAmisSecours/templates/RandoAmisSecours/outing/details.html
{% extends 'RandoAmisSecours/base.html' %}
{% load static l10n i18n %}

{% block title %}{% blocktrans with outing.name as name %}Outing «{{ name }}»{% endblocktrans %}{% endblock %}

{% block head %}
  <link rel="stylesheet" href="{% get_static_prefix %}RandoAmisSecours/css/leaflet-v0.7.7.css" />
  <link rel="stylesheet" href="{% get_static_prefix %}RandoAmisSecours/css/leaflet.fullscreen-v1.0.1.css" />
{% endblock %}

{% block style %}
    #map { height: 300px; }
{% endblock %}

{% block nav-outings %}active{% endblock %}

{% block breadcrumb %}
  <li><a href="{% url 'index' %}">{% trans "Home" %}</a></li>
  <li><a href="{% url 'outings.index' %}">{% trans "Outings" %}</a></li>
  <li class="active">{{ outing.name }}</li>
{% endblock %}

{% block body %}
<h2>{{ outing.name }}{% if outing.status != FINISHED and outing.user == user %} <small><a href="{% url 'outings.update' outing.pk %}">({% trans "update" %})</a></small>{% endif %}</h2>

<div class="row">
  {% if messages %}
  <div class="span12">
    {% for message in messages %}
    <div class="alert alert-{{ message.tags|default:'danger' }}">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <strong>{{ message.tags|default:'danger'|capfirst }}:</strong> {{ message }}
    </div>
    {% endfor %}
  </div>
  {% endif %}
  {% if outing.status == DRAFT %}
  <div class="span12">
    <div class="alert alert-warning">
      {% url 'outings.confirm' outing.pk as confirmed_url %}
      <strong>{% trans "Warning:" %}</strong> {% blocktrans %}This outing is not validated. You should <a href="{{ confirmed_url }}">confirmed it!</a>{% endblocktrans %}
    </div>
  </div>
  {% endif %}
  {% if outing.status == CONFIRMED %}
  <div class="col-md-12">
    <div class="progress">
      {% with outing.getPercents as percents %}
      <div class="progress-bar progress-bar-success" style="width: {{ percents.0|unlocalize }}%"></div>
      <div class="progress-bar progress-bar-warning" style="width: {{ percents.1|unlocalize }}%"></div>
      <div class="progress-bar progress-bar-danger" style="width: {{ percents.2|unlocalize }}%"></div>
      {% endwith %}
    </div>
  </div>
  {% endif %}
  <div class="col-md-6">
    <dl class="dl-horizontal">
      <dt>{% trans "Begin" %}</dt>
      <dd>{{ outing.beginning }}</dd>
      <dt>{% trans "End" %}</dt>
      <dd>{{ outing.ending }}</dd>
      <dt>{% trans "Alert at" %}</dt>
      <dd>{{ outing.alert }}</dd>
    </dl>
  </div>
  <div class="col-md-6">
    <dl class="dl-horizontal">
      <dt>{% trans "Description" %}</dt>
      <dd>{{ outing.description|urlize }}</dd>
    </dl>
  </div>
  <div class="col-md-6 col-md-offset-3">
    <div id="map">
    </div>
  </div>
  {% if user.is_authenticated and outing.status == CONFIRMED and outing.is_alerting %}
  <div class="col-md-6">
    <h4 class="modal-header">{% trans "Late outing" %}</h4>
    <p>{% blocktrans with outing.user.get_full_name as full_name %}{{ full_name }} is really late, you can try to contact him:{% endblocktrans %}</p>
    <dl class="dl-horizontal">
      <dt>{% trans "Name" %}</dt>
      <dd>{{ outing.user.get_full_name }}</dd>
      <dt>{% trans "Phone number" %}</dt>
      <dd>{% if outing.user.profile.phone_number %}<a href="tel:{{ outing.user.profile.phone_number }}">{{ outing.user.profile.phone_number }}</a>{% else %}?{% endif %}</dd>
    </dl>
  </div>
  {% if outing.gpspoint_set.count %}
  <div class="col-md-6">
    <h4 class="modal-header">{% trans "GPS trace" %}</h4>
    {% url "outings.details.trace" outing.pk as URL %}
    <p>{% blocktrans %}A GPS trace has been recorded, you can <a href="{{ URL }}">watch it</a>.{% endblocktrans %}</p>
  </div>
  {% endif %}
  {% endif %}
</div>
{% endblock %}

{% block script %}
<script src="{% get_static_prefix %}RandoAmisSecours/js/leaflet-v0.7.7.js"></script>
<script src="{% get_static_prefix %}RandoAmisSecours/js/Leaflet.fullscreen.min-v1.0.1.js"></script>
<script>
  $(function(){
    var map = L.map('map', {
                      fullscreenControl: {
                        pseudoFullscreen: true
                      }
                  }).setView([{{ outing.latitude|unlocalize }}, {{ outing.longitude|unlocalize }}], 12);
    L.tileLayer('//{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
        attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors',
        maxZoom: 18}).addTo(map);
    var marker = L.marker([{{ outing.latitude|unlocalize }}, {{ outing.longitude|unlocalize }}]).addTo(map)
                    .bindPopup('Ending');
  });
</script>
{% endblock %}